# ==========================================
# CONFIGURATION RETROPOCKET
# ==========================================

# --- IDENTIFIANTS & ACCÈS ---
SUDOMDP="******"
WIFI_INTERFACE="wlan0"

# --- MATÉRIEL & PERFORMANCE ---
GOVERNOR="performance"           # performance, schedutil, powersave
READ_AHEAD=2048                  # 1024 (standard), 2048 (rapide), 4096 (max)
DISK_DEV="/dev/mmcblk0"

# --- VIDÉO (Streaming) ---
VIDEO_DEVICE="/dev/dri/card0"
VIDEO_FPS=60                     # 30 (éco), 60 (fluide)
VIDEO_BITRATE="2M"               # 1M (bas), 2M (moyen), 4M (haute qualité)
VIDEO_BUFSIZE="500k"             # 250k, 500k, 1M (tampon d'encodage)
VIDEO_GOP=30                     # 30 ou 60 (intervalle d'image clé)
VIDEO_DEST="127.0.0.1:8004"

# --- AUDIO (Streaming) ---
AUDIO_SOURCE="alsa_output.platform-hdmi-sound.stereo-fallback.monitor"
AUDIO_LATENCY=5                  # 5 (ultra-bas), 10 (bas), 20 (stable)
AUDIO_BITRATE="64k"              # 32k (voix/éco), 64k (standard), 96k (haute-fidélité)
AUDIO_FRAME_DUR=20               # 10 (instable), 20 (recommandé), 40 (stable)
AUDIO_SAMPLERATE=48000           # 44100 (CD), 48000 (standard WebRTC)
AUDIO_DEST="localhost:5004"

# --- CHEMINS SYSTÈME ---
EMU_BIN="/usr/local/bin/emulationstation" # ou /usr/bin/retroarch
BACKEND_BIN="/home/retropocket/retropocket/back/retropocket-back"
BLUETOOTH_SCRIPT="/home/retropocket/blue.sh"

# --- GESTION RESET & UPDATES ---
TRIGGER_FILE="/home/retropocket/sdcard/.reset"
RESET_SRC_DIR="/home/retropocket/original/retropocket"
RESET_NETPLAN_FILE="/home/retropocket/original/retropocket/network/wifi.yaml"
TMP_DIR="/tmp/retropocket"
DEST_DIR="/home/retropocket"
