# --- IDENTIFIANTS ---
SUDOMDP="retro1234!"

# --- HARDWARE & PERF ---
GOVERNOR="{{governor}}"
WIFI_INTERFACE="wlan0"
DISK_DEV="/dev/mmcblk0"
READ_AHEAD={{readAhead}}

# --- OPTIONS GÉNÉRALES ---
ENABLE_VIDEO={{videoCapture}}              # true pour activer, false pour désactiver
ENABLE_AUDIO={{audioCapture}}

# --- CHEMINS & RESET ---
TRIGGER_FILE="/home/retropocket/sdcard/.reset"
RESET_SRC_DIR="/home/retropocket/sdcard/dev/retropocket"
RESET_NETPLAN_FILE="/home/retropocket/sdcard/dev/retropocket/network/wifi.yaml"
TMP_DIR="/home/retropocket/sdcard/dev/tmp"
DEST_DIR="/home/retropocket"

# --- STREAMING VIDÉO ---
VIDEO_DEVICE="/dev/dri/card0"
VIDEO_FPS={{fps}}
VIDEO_BITRATE="{{videoBitrate}}"
VIDEO_BUFSIZE="{{buffer}}"
VIDEO_GOP={{gop}}
VIDEO_DEST="127.0.0.1:8004"

# --- STREAMING AUDIO ---
AUDIO_SOURCE="alsa_output.platform-hdmi-sound.stereo-fallback.monitor"
AUDIO_LATENCY={{audioLatency}}
AUDIO_BITRATE="{{audioBitrate}}"
AUDIO_FRAME_DUR={{audioFrameDur}}
AUDIO_SAMPLERATE={{audioSampleRate}}
AUDIO_DEST="localhost:5004"

# --- EXÉCUTABLES ---
EMU_BIN="{{interface}}"
BACKEND_BIN="/home/retropocket/retropocket/back/retropocket-back"
